service: serveless-example
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x

plugins:
  - serverless-bundle
  - serverless-offline-env
  - serverless-offline
  - serverless-dotenv-plugin
  - serverless-prune-plugin

custom:
  bundle:
    tsConfig: 'tsconfig.build.json'
  serverless-offline-env:
    path: ./env/.env.staging
  dotenv:
    basePath: ./env/
    logging: false
  prune:
    automatic: true
    includeLayers: true
    number: 1

functions:
  hello:
    handler: src/handler.hello
    events:
      - http:
          path: hello
          method: get
